### ISSUE TITLE
Upcoming linter changes

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-bailey#3]
We're in the process of replacing `linter` with a rewrite. Our central issue for tracking the plan is https://github.com/AtomLinter/linter-plus/issues/29. We're working hard to make this a smooth transition for you and for your users.

Please let us know here if you'd prefer to do the work yourself. If you have any questions or concerns please join us in our [room on gitter](https://gitter.im/AtomLinter/Linter).

**Comment by relekang** [comment]
Is there any documentation of the differences in the API?

**Comment by AsaAyers** [comment]
The documentation has started at https://github.com/AtomLinter/linter-plus/wiki/Linter-API, and now that I'm looking at it I see it's slightly out of date.

The core differences are:
1. You don't have to extend from a base class
2. Instead of being passed a filename and a callback you get passed the `textEditor` and a `textBuffer` and you return a `Promise` or an array of errors.

**Comment by relekang** [comment]
Sounds great, I will look into porting this package :)
