### ISSUE TITLE
No description for the package in package.json

### ISSUE THREAD

**Issue by euxaristia** [AtomLinter/linter-bailey#5]
A short description should be put so users on Atom get a quick idea of the package

**Comment by relekang** [comment]
I don't have the time to fix this, but PR would be appreciated.

**Comment by euxaristia** [comment]
OK, I'll add a similar description to other packages and make a PR

**Comment by euxaristia** [comment]
https://github.com/AtomLinter/linter-bailey/pull/6 @relekang

**Comment by relekang** [comment]
Thanks, I'll see if I can get it released tonight :v:

**Comment by Arcanemagus** [comment]
This was fixed in #6.
